- name: Setup and Configure K3S Server Node
  hosts: server
  gather_facts: true
  roles:
    - role: k3s_server
      become: true

- name: Setup and Configure K3S Agent Node
  hosts: agent
  gather_facts: true
  roles:
    - role: k3s_agent
      become: true
